name: deploy-evcs-stub
description: Deploy the EVCS stub to a given environment
inputs:
  role-to-assume:
    required: true
    description: The AWS role to assume for the deploymnet
  artifact-bucket-name:
    required: true
    description: The S3 bucket to upload the artefact to
  signing-profile-name:
    required: true
    description: The signing profile used to sign code on upload
runs:
  using: composite
  steps:
    - name: Set up AWS creds
      uses: aws-actions/configure-aws-credentials@v4.2.1
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: eu-west-2

    - name: Deploy SAM app
      uses: govuk-one-login/devplatform-upload-action@v3.9
      with:
        artifact-bucket-name: ${{ inputs.artifact-bucket-name }}
        signing-profile-name: ${{ inputs.signing-profile-name }}
        working-directory: ./di-ipv-evcs-stub/deploy
        template-file: .aws-sam/build/template.yaml
