# ---- Build stage ----
ARG SHA_256=sha256:565d3643a78a657ca03e85c110af9579a07e833d6bcc14f475249c521b5c5d74 
FROM --platform=$BUILDPLATFORM openjdk:17.0.1-jdk-slim@${SHA_256} AS build

WORKDIR /home/gradle/src
COPY gradlew build.gradle ./
COPY gradle gradle
COPY src src

RUN ./gradlew build --no-daemon

# ---- Runtime stage ----
FROM --platform=$BUILDPLATFORM openjdk:17.0.1-jdk-slim@${SHA_256} AS runtime
ARG TARGETARCH
ARG TARGETOS

ENV PORT=8085 DEBUG_PORT=8087
ENV JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}

RUN addgroup --system --gid 1001 appgroup && adduser --system --uid 1001 appuser --gid 1001

COPY --from=build \
    /home/gradle/src/build/distributions/src.tar \
    /app/

WORKDIR /app

EXPOSE ${PORT} ${DEBUG_PORT}

ENTRYPOINT ["./src/bin/src"]
LABEL project="di-ipv-core-stub"
# Stage with no dynatrace agent which requires volume mount for config
# i.e A Docker-compose file can be used to mount the config at runtime
# ---- nodynatrace Runtime stage ----
FROM runtime AS nodynatrace
RUN tar -xvf src.tar && rm src.tar \
&& chown -R appuser:appgroup /app

USER appuser
# Stage with dynatrace agent with config baked in
# This the final default stage for normal use
# ---- dynatrace Runtime stage ----
FROM runtime AS dynatrace

USER root

ADD config config

ENV DT_HOME="/opt/dynatrace/oneagent"
RUN --mount=type=secret,id=dt_token \
    DT_API_TOKEN=$(cat /run/secrets/dt_token) && \
    mkdir -p "$DT_HOME" \
    && apt-get update \
    && apt-get install -y curl wget unzip \
    && wget -O "$DT_HOME/oneagent.zip" "https://khw46367.live.dynatrace.com/api/v1/deployment/installer/agent/unix/paas/latest?flavor=default&include=java&arch=arm&Api-Token=$DT_API_TOKEN" \
    && unzip -d "$DT_HOME" "$DT_HOME/oneagent.zip" \
    && rm "$DT_HOME/oneagent.zip" \
    && tar -xvf src.tar && rm src.tar \
    && chown -R appuser:appgroup /app "$DT_HOME" \
    && apt-get remove -y wget unzip && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

ENV LD_PRELOAD=/opt/dynatrace/oneagent/agent/lib64/liboneagentproc.so

USER appuser
