ARG DT_API_TOKEN
FROM --platform="linux/arm64" amazoncorretto:21.0.6-al2@sha256:c0643148d077b3917bf6c085aaa1ac35ff1f202344ab8691cc0f5953f9b97f8e AS build
ARG DT_API_TOKEN
COPY . /home/gradle/src
WORKDIR /home/gradle/src
RUN --mount=type=secret,id=GITHUB_TOKEN,env=GITHUB_TOKEN \
    ./gradlew build --no-daemon

FROM --platform="linux/arm64" amazoncorretto:21.0.6-al2@sha256:c0643148d077b3917bf6c085aaa1ac35ff1f202344ab8691cc0f5953f9b97f8e
ARG DT_API_TOKEN
ENV PORT 8084
ENV JAVA_TOOL_OPTIONS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
RUN yum update -y && yum install -y shadow-utils curl tar wget unzip
RUN groupadd --system --gid 1001 appgroup && useradd --system --uid 1001 appuser --gid 1001
RUN mkdir /app
COPY --from=build \
    /home/gradle/src/build/distributions/di-ipv-credential-issuer-stub.tar \
    /app/

WORKDIR /app

RUN tar -xvf di-ipv-credential-issuer-stub.tar \
    && rm di-ipv-credential-issuer-stub.tar

ENV DT_HOME="/opt/dynatrace/oneagent"
RUN mkdir -p "$DT_HOME"
RUN wget -O "$DT_HOME/oneagent.zip" "https://khw46367.live.dynatrace.com/api/v1/deployment/installer/agent/unix/paas/latest?flavor=default&include=java&arch=arm&Api-Token=$DT_API_TOKEN"
RUN unzip -d "$DT_HOME" "$DT_HOME/oneagent.zip"
RUN rm "$DT_HOME/oneagent.zip"
ENV LD_PRELOAD /opt/dynatrace/oneagent/agent/lib64/liboneagentproc.so

RUN chown -R appuser:appgroup /app/
USER appuser


EXPOSE $PORT
EXPOSE 5006

ENTRYPOINT ["./di-ipv-credential-issuer-stub/bin/di-ipv-credential-issuer-stub"]
LABEL project="di-ipv-credential-issuer-stub"
