openapi: 3.0.3
info:
  title: "DCMAW Async Stub"
  description: "The api presented by DCMAW async stub"
  version: "1.0.0"
paths:
  /healthcheck:
    get:
      description: "returns a 200 for Route53 health checks to use"
      responses:
        200:
          description: "A healthcheck response"
          content:
            application/json:
              schema:
                type: "object"
      x-amazon-apigateway-integration:
        type: "MOCK"
        requestTemplates:
          application/json: "{\"statusCode\":200}"
        responses:
          200:
            statusCode: 200
            responseTemplates:
              application/json: "{\"healthcheck\": \"ok\"}"
  /async/token:
    post:
      description: Returns an access token
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/TokenRequestBody"
      responses:
        200:
          description: "Success response "
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponseBody"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetDcmawAsyncAccessTokenFunction.Arn}:live/invocations
        passthroughBehavior: "WHEN_NO_TEMPLATES"
        responses:
          default:
            statusCode: 200
            responseTemplates:
              application/json: '{"result": "success"}'

  /async/credential:
    post:
      description: Returns a pending credential
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CredentialRequestBody"
      responses:
        201:
          description: "Success response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CredentialResponseBody"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetDcmawAsyncVcFunction.Arn}:live/invocations
        passthroughBehavior: "WHEN_NO_TEMPLATES"
        responses:
          default:
            statusCode: 201
            responseTemplates:
              application/json: '{"result": "success"}'

  /management/enqueueVc:
    post:
      description: Generates and pushes VC onto queue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ManagementEnqueueVcRequestBody"
      responses:
        201:
          description: "Success response"
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManagementEnqueueVcFunction.Arn}:live/invocations
        passthroughBehavior: "WHEN_NO_TEMPLATES"
        responses:
          default:
            statusCode: 201
            responseTemplates:
              application/json: '{"result": "success"}'

  /management/generateVc:
    post:
      description: Generates and returns a VC - for setting up test scenarios
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ManagementGenerateVcRequestBody"
      responses:
        200:
          description: "Success response"
          content:
            text/plain:
              schema:
                type: string
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManagementGenerateVcFunction.Arn}:live/invocations
        passthroughBehavior: "WHEN_NO_TEMPLATES"
        responses:
          default:
            statusCode: 200
            responseTemplates:
              application/json: '{"result": "success"}'

  /management/cleanupDcmawState:
    post:
      description: Cleans up DCMAW session state from stub given a user id.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ManagementCleanupDCMAWStateRequestBody"
      responses:
        200:
          description: "Success response"
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManagementCleanupSessionFunction.Arn}:live/invocations
        passthroughBehavior: "WHEN_NO_TEMPLATES"
        responses:
          default:
            statusCode: 201
            responseTemplates:
              application/json: '{"result": "success"}'

  /management/enqueueError:
    post:
      description: Generates and pushes error onto queue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ManagementEnqueueErrorRequestBody"
      responses:
        201:
          description: "Success response"
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ManagementEnqueueErrorFunction.Arn}:live/invocations
        passthroughBehavior: "WHEN_NO_TEMPLATES"
        responses:
          default:
            statusCode: 201
            responseTemplates:
              application/json: '{"result": "success"}'

components:
  schemas:
    TokenRequestBody:
      description: Request body for token request
      required:
        - grant_type
      type: object
      properties:
        grant_type:
          type: string
          description: The grant type - should be "client_credentials"
    TokenResponseBody:
      description: Response body from the asyncToken endpoint
      required:
        - access_token
        - token_type
        - expires_in
      properties:
        access_token:
          type: string
          description: The access token
        token_type:
          type: string
          description: The token type - should be "Bearer"
        expires_in:
          type: integer
          description: The length of time the token is valid for in seconds
    CredentialRequestBody:
      description: Request body for credential request
      type: object
      required:
        - client_id
        - sub
        - govuk_signin_journey_id
        - state
      properties:
        client_id:
          type: string
          description: The client ID
        sub:
          type: string
          description: The user ID of the subject
        govuk_signin_journey_id:
          type: string
          description: Journey id
        state:
          type: string
          description: A random value
        redirect_uri:
          type: string
          description: The url for the app to redirect to in the MAM journey
    CredentialResponseBody:
      description: Response body from the asyncCredential endpoint
      type: object
      required:
        - sub
        - "https://vocab.account.gov.uk/v1/credentialStatus"
      properties:
        sub:
          type: string
          description: The user ID of the subject
        "https://vocab.account.gov.uk/v1/credentialStatus":
          type: string
          description: The status of the credential. Should be "pending"
    ManagementEnqueueVcRequestBody:
      description: Request body for enqueueing a VC
      type: object
      required:
        - user_id
      properties:
        user_id:
          type: string
          description: The id of a user that has an already-initialised session
        delay_seconds:
          type: number
          description: Optional number of seconds to delay delivery of the message (default=0)
        queue_name:
          type: string
          description: Optional queue name to override the stub's default.
        # Properties for selecting pre-canned VC data
        test_user:
          type: string
          enum: [kennethD]
          description: The name/id of the test user to generate a VC for
        document_type:
          type: string
          enum: [ukChippedPassport]
          description: The document type of the VC
        evidence_type:
          type: string
          enum: [success, fail]
          description: The evidence type of the VC
        ci:
          type: array
          description: Optional array of CI codes
        # Properties for just passing in the full data blocks for the VC
        credential_subject:
          type: object
          description: The credential subject block for the VC
        evidence:
          type: object
          description: The evidence block for the VC
        nbf:
          type: number
          description: Optional value for nbf field
    ManagementGenerateVcRequestBody:
      description: Request body for generating a VC
      type: object
      required:
        - user_id
      properties:
        user_id:
          type: string
          description: The id of a user that has an already-initialised session
        credential_subject:
          type: object
          description: The credential subject block for the VC
        evidence:
          type: object
          description: The evidence block for the VC
        nbf:
          type: number
          description: Optional value for nbf field
    ManagementCleanupDCMAWStateRequestBody:
      description: Request body for cleaning up DCMAW state given a user id.
      type: object
      required:
        - user_id
      properties:
        user_id:
          type: string
          description: The id of a user that has an already-initialised session
    ManagementEnqueueErrorRequestBody:
      description: Request body for enqueueing an error
      type: object
      required:
        - user_id
        - error_code
      properties:
        user_id:
          type: string
          description: The id of a user that has an already-initialised session
        error_code:
          type: string
          description: An error code for example 'access_denied'
        error_description:
          type: string
          description: An optional error description
        delay_seconds:
          type: number
          description: Optional number of seconds to delay delivery of the message (default=0)
