enum AllState {
    CURRENT = "CURRENT",
    PENDING = "PENDING",
    VERIFICATION = "VERIFICATION",
    ABANDONED = "ABANDONED",
    PENDING_RETURN = "PENDING_RETURN",
    HISTORIC = "HISTORIC",
    VERIFICATION_ARCHIVED = "VERIFICATION_ARCHIVED"
  }

  export default AllState;
