AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 30

Description: >-
  This creates the lambda functions to stub CIMIT lambdas for getContraIndicators, getContraIndicatorCredential, 
  putContraIndicators and postMitigations.

Parameters:
  VpcStackName:
    Description: >
      The name of the stack that defines the VPC in which this container will
      run.
    Type: String
  Environment:
    Description: The name of the environment to deploy to.
    Type: String
    AllowedPattern: ((production)|(build)|(dev.*))
  PermissionsBoundary:
    Description: "The ARN of the permissions boundary to apply when creating IAM roles"
    Type: String
    Default: "none"

Conditions:
  IsDevelopment: !Or
    - !Equals [ !Ref AWS::AccountId, "130355686670"]
    - !Equals [ !Ref AWS::AccountId, "175872367215"]
  IsOldDevelopment: !Equals [ !Ref AWS::AccountId, "130355686670"]
  IsNewDevelopment: !Equals [ !Ref AWS::AccountId, "175872367215"]
  IsNotDevelopment: !Not [ !Condition IsDevelopment ]
  IsProduction: !Equals [ !Ref Environment, "production"]
  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"
Resources:
  # lambda to stub cimit getContraIndicators
  GetContraIndicatorsFunction:
    Type: AWS::Serverless::Function
    # checkov:skip=CKV_AWS_109: this requires a broad set of permissions
    DependsOn:
      - "GetContraIndicatorsFunctionLogGroup"
    Properties:
      FunctionName: !Sub "getContraIndicators-${Environment}"
      CodeUri: "../lambdas/get-contra-indicators"
      Handler: uk.gov.di.ipv.core.getcontraindicators.GetContraIndicatorsHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      Architectures:
        - arm64
      MemorySize: 2048
      Tracing: Active
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${Environment}"
      VpcConfig:
        SubnetIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-ProtectedSubnetIdA
          - Fn::ImportValue: !Sub ${VpcStackName}-ProtectedSubnetIdB
        SecurityGroupIds:
          - !GetAtt CimitLambdaSecurityGroup.GroupId
      Policies:
        - VPCAccessPolicy: { }
        - SSMParameterReadPolicy:
            ParameterName: !Sub ${Environment}/stubs/*

  # lambda to stub cimit postMitigations
  PostMitigationsFunction:
    Type: AWS::Serverless::Function
    # checkov:skip=CKV_AWS_109: this requires a broad set of permissions
    DependsOn:
      - "PostMitigationsFunctionLogGroup"
    Properties:
      FunctionName: !Sub "postMitigations-${Environment}"
      CodeUri: "../lambdas/post-mitigations"
      Handler: uk.gov.di.ipv.core.postmitigations.PostMitigationsHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      Architectures:
        - arm64
      MemorySize: 2048
      Tracing: Active
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${Environment}"
      VpcConfig:
        SubnetIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-ProtectedSubnetIdA
          - Fn::ImportValue: !Sub ${VpcStackName}-ProtectedSubnetIdB
        SecurityGroupIds:
          - !GetAtt CimitLambdaSecurityGroup.GroupId
      Policies:
        - VPCAccessPolicy: { }
        - SSMParameterReadPolicy:
            ParameterName: !Sub ${Environment}/stubs/*

  # lambda to stub cimit putContraIndicators
  PutContraIndicatorsFunction:
    Type: AWS::Serverless::Function
    # checkov:skip=CKV_AWS_109: this requires a broad set of permissions
    DependsOn:
      - "PutContraIndicatorsFunctionLogGroup"
    Properties:
      FunctionName: !Sub "putContraIndicators-${Environment}"
      CodeUri: "../lambdas/put-contra-indicators"
      Handler: uk.gov.di.ipv.core.putcontraindicators.PutContraIndicatorsHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      Architectures:
        - arm64
      MemorySize: 2048
      Tracing: Active
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${Environment}"
      VpcConfig:
        SubnetIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-ProtectedSubnetIdA
          - Fn::ImportValue: !Sub ${VpcStackName}-ProtectedSubnetIdB
        SecurityGroupIds:
          - !GetAtt CimitLambdaSecurityGroup.GroupId
      Policies:
        - VPCAccessPolicy: { }
        - SSMParameterReadPolicy:
            ParameterName: !Sub ${Environment}/stubs/*

  GetContraIndicatorsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 14
      LogGroupName: !Sub "/aws/lambda/getContraIndicators-${Environment}"
      KmsKeyId: !GetAtt LoggingKmsKey.Arn

  PostMitigationsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 14
      LogGroupName: !Sub "/aws/lambda/postMitigations-${Environment}"
      KmsKeyId: !GetAtt LoggingKmsKey.Arn

  PutContraIndicatorsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 14
      LogGroupName: !Sub "/aws/lambda/putContraIndicators-${Environment}"
      KmsKeyId: !GetAtt LoggingKmsKey.Arn

  CimitLambdaSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: >-
        CIMIT Lambdas Security Group
      SecurityGroupIngress:
        - CidrIp:
            Fn::ImportValue: !Sub ${VpcStackName}-VpcCidr
          Description: Allow ingress traffic from vpc cidr to port 443
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
      VpcId:
        Fn::ImportValue: !Sub ${VpcStackName}-VpcId

  CimitStubTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # checkov:skip=CKV_AWS_28: Point in time recovery is not necessary for this table.
      TableName: !Sub "cimit-stub-${Environment}"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
        - AttributeName: "contraIndicatorCode"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
        - AttributeName: "contraIndicatorCode"
          KeyType: "RANGE"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
        KMSMasterKeyId: !GetAtt DynamoDBKmsKey.Arn

  DynamoDBKmsKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - kms:*
            Resource: "*"
          - Effect: Allow
            Principal:
              Service: "dynamodb.amazonaws.com"
            Action:
              - "kms:Encrypt*"
              - "kms:Decrypt*"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:Describe*"
            Resource: "*"
            Condition:
              StringEquals:
                "kms:CallerAccount": !Sub "${AWS::AccountId}"
                "kms:ViaService":
                  - "dynamodb.amazonaws.com"
                  - !Sub "lambda.${AWS::Region}.amazonaws.com"

  # kms key for logging
  LoggingKmsKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - kms:*
            Resource: "*"
          - Effect: Allow
            Principal:
              Service: !Sub "logs.${AWS::Region}.amazonaws.com"
            Action:
              - "kms:Encrypt*"
              - "kms:Decrypt*"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:Describe*"
            Resource: "*"
            Condition:
              ArnLike:
                "kms:EncryptionContext:aws:logs:arn": !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"

  StubManagementAPI:
    Type: AWS::Serverless::Api
    Properties:
      # checkov:skip=CKV_AWS_120: We are not implementing API Gateway caching at the time.
      Name: !Sub IPV Core Stub Management API Gateway ${Environment}
      EndpointConfiguration:
        Type: PRIVATE
        VPCEndpointIds: !If
          - IsOldDevelopment
          - - !ImportValue "network-shared-development-ApiGatewayVpcEndpointId"
          - - Fn::ImportValue: !Sub "${VpcStackName}-ExecuteApiGatewayEndpointId"
      DefinitionBody:
        openapi: "3.0.3" # workaround to get `sam validate` to work
        paths: # workaround to get `sam validate` to work
          /foo:
            bar: baz # workaround to get `sam validate` to work
        Fn::Transform:
          Name: "AWS::Include"
          Parameters:
            Location: "../openAPI/core-stub_management-internal.yaml"
      # Set authentication settings
      Auth:
        ResourcePolicy:
          CustomStatements:
            - Action: 'execute-api:Invoke'
              Effect: Allow
              Principal: '*'
              Resource:
                - 'execute-api:/*'
            - Action: 'execute-api:Invoke'
              Effect: Deny
              Principal: '*'
              Resource:
                - 'execute-api:/*'
              Condition:
                StringNotEquals:
                  'aws:SourceVpce': !If
                    - IsOldDevelopment
                    - !ImportValue "network-shared-development-ApiGatewayVpcEndpointId"
                    - Fn::ImportValue:
                        !Sub "${VpcStackName}-ExecuteApiGatewayEndpointId"
      # Set the API Gateway stage name, trac'g, access log settings
      StageName: !Sub ${Environment}
      TracingEnabled: true
      AccessLogSetting:
        DestinationArn: !GetAtt StubManagementAPILogGroup.Arn
        Format: >-
          {
          "requestId":"$context.requestId",
          "ip":"$context.identity.sourceIp",
          "requestTime":"$context.requestTime",
          "httpMethod":"$context.httpMethod",
          "path":"$context.path",
          "routeKey":"$context.routeKey",
          "status":"$context.status",
          "protocol":"$context.protocol",
          "responseLatency":"$context.responseLatency",
          "responseLength":"$context.responseLength"
          }

  StubManagementAPILogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      #Set the log group name based on the environment
      LogGroupName: !If
        - IsNewDevelopment
        - !Sub /aws/vendedlogs/apigateway/${AWS::StackName}-CoreCimitStubPrivate-API-GW-AccessLogs
        - !Sub /aws/apigateway/${AWS::StackName}-CoreCimitStubPrivate-API-GW-AccessLogs
      RetentionInDays: 14
      KmsKeyId: !GetAtt LoggingKmsKey.Arn

  StubManagementAPILogGroupSubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    Condition: IsNotDevelopment
    Properties:
      # Set the destination for the log filter subscription
      DestinationArn: "arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython"
      FilterPattern: ""
      LogGroupName: !Ref StubManagementAPILogGroup

  StubManagementApiGateWayIamRoleStubManagementApiGateWayIamRole:
    Type: AWS::IAM::Role
    Properties:
      # Define the IAM role for the API Gateway
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      #Set the policies for the IAM Role
      Policies:
        - PolicyName: AllowApiGatewayToInvokeStartSyncExecution
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'states:StartSyncExecution'
                Resource:  "arn:aws:lambda:eu-west-2:175872367215:function:putContraIndicators-${Environment}"
      # Set the permissions boundary if specified
      PermissionsBoundary: !If
        - UsePermissionsBoundary
        - !Ref PermissionsBoundary
        - !Ref AWS::NoValue
