AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 30

Description: >-
  This creates the lambda function to stub CIMIT lambda's for getContraIndicators, getContraIndicatorCredential, 
  putContraIndicators and postMitigations.

Parameters:
  VpcStackName:
    Description: >
      The name of the stack that defines the VPC in which this container will
      run.
    Type: String
  Environment:
    Description: The name of the environment to deploy to.
    Type: String
    AllowedPattern: ((production)|(build)|(dev.*))

Conditions:
  IsDevelopment: !Not
    - !Or
      - !Equals [ !Ref Environment, "build"]
      - !Equals [ !Ref Environment, "production"]
  IsProduction: !Equals [ !Ref Environment, production ]
  IsNonProd: !Not
    - !Or
      - !Condition IsDevelopment
      - !Condition IsProduction

Resources:
  # lambda to replicate cimit getContraIndicators
  GetContraIndicatorsLambda:
    Type: AWS::Serverless::Function
    # checkov:skip=CKV_AWS_109: this requires a broad set of permissions
    DependsOn:
      - "GetContraIndicatorsFunctionLogGroup"
    Properties:
      FunctionName: !Sub "get-contra-indicators-${Environment}"
      CodeUri: "../lambdas/get-contra-indicators"
      Handler: uk.gov.di.ipv.core.getcontraindicators.GetContraIndicatorsHandler::handleRequest
      Runtime: java17
      PackageType: Zip
      Architectures:
        - arm64
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${Environment}"
      VpcConfig:
        SubnetIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-ProtectedSubnetIdA
          - Fn::ImportValue: !Sub ${VpcStackName}-ProtectedSubnetIdB
        SecurityGroupIds:
          - !GetAtt CimitLambdaSecurityGroup.GroupId
      Policies:
        - VPCAccessPolicy: { }
        - Statement:
            - Sid: EnforceStayinSpecificVpc
              Effect: Allow
              Action:
                - 'lambda:CreateFunction'
                - 'lambda:UpdateFunctionConfiguration'
              Resource:
                - "*"
              Condition:
                StringEquals:
                  "lambda:VpcIds":
                    - Fn::ImportValue: !Sub ${VpcStackName}-VpcId
        - Statement:
            - Sid: AllowKMS
              Effect: Allow
              Action:
                - "kms:Decrypt"
                - "kms:GenerateDataKey*"
                - "kms:DescribeKey"
              Resource:
                - !Sub "arn:aws:kms:eu-west-2:${AWS::AccountId}:key/*"
              Condition:
                "ForAnyValue:StringLike":
                  "kms:ResourceAliases":
                    - "alias/sqs/QueuesKmsKey"
        - Statement:
            - Sid: AllowKMSSign
              Effect: Allow
              Action:
                - "kms:Sign"
              Resource:
                - !Sub "arn:aws:kms:eu-west-2:${AWS::AccountId}:key/*"
              Condition:
                "ForAnyValue:StringLike":
                  "kms:ResourceAliases":
                    - "alias/sqs/SignJwtKmsKey"
        - Statement:
            - Sid: AllowSecretsManagerGet #pragma: allowlist secret
              Effect: Allow
              Action:
                - "secretsmanager:GetSecretValue" #pragma: allowlist secret
                - "secretsmanager:ListSecrets" #pragma: allowlist secret
              Resource:
                - !Sub "arn:aws:secretsmanager:eu-west-2:${AWS::AccountId}:secret:/stubs/queue/*" #pragma: allowlist secret
        - Statement:
            - Sid: AllowGetSSMParam
              Effect: Allow
              Action:
                - "ssm:GetParameter"
              Resource:
                - !Sub "arn:aws:ssm:eu-west-2:${AWS::AccountId}:parameter/stubs/*"

  GetContraIndicatorCredentialLambda:
    Type: AWS::Serverless::Function
    # checkov:skip=CKV_AWS_109: this requires a broad set of permissions
    DependsOn:
      - "GetContraIndicatorCredentialFunctionLogGroup"
    Properties:
      FunctionName: !Sub "get-contra-indicator-credential-${Environment}"
      CodeUri: "../lambdas/get-contra-indicator-credential"
      Handler: uk.gov.di.ipv.core.getcontraindicatorcredential.GetContraIndicatorCredentialHandler::handleRequest
      Runtime: java17
      PackageType: Zip
      Architectures:
        - arm64
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${Environment}"
      VpcConfig:
        SubnetIds:
          - Fn::ImportValue: !Sub ${VpcStackName}-ProtectedSubnetIdA
          - Fn::ImportValue: !Sub ${VpcStackName}-ProtectedSubnetIdB
        SecurityGroupIds:
          - !GetAtt CimitLambdaSecurityGroup.GroupId
      Policies:
        - VPCAccessPolicy: { }
        - Statement:
            - Sid: EnforceStayinSpecificVpc
              Effect: Allow
              Action:
                - 'lambda:CreateFunction'
                - 'lambda:UpdateFunctionConfiguration'
              Resource:
                - "*"
              Condition:
                StringEquals:
                  "lambda:VpcIds":
                    - Fn::ImportValue: !Sub ${VpcStackName}-VpcId
        - Statement:
            - Sid: AllowKMS
              Effect: Allow
              Action:
                - "kms:Decrypt"
                - "kms:GenerateDataKey*"
                - "kms:DescribeKey"
              Resource:
                - !Sub "arn:aws:kms:eu-west-2:${AWS::AccountId}:key/*"
              Condition:
                "ForAnyValue:StringLike":
                  "kms:ResourceAliases":
                    - "alias/sqs/QueuesKmsKey"
        - Statement:
            - Sid: AllowKMSSign
              Effect: Allow
              Action:
                - "kms:Sign"
              Resource:
                - !Sub "arn:aws:kms:eu-west-2:${AWS::AccountId}:key/*"
              Condition:
                "ForAnyValue:StringLike":
                  "kms:ResourceAliases":
                    - "alias/sqs/SignJwtKmsKey"
        - Statement:
            - Sid: AllowSecretsManagerGet #pragma: allowlist secret
              Effect: Allow
              Action:
                - "secretsmanager:GetSecretValue" #pragma: allowlist secret
                - "secretsmanager:ListSecrets" #pragma: allowlist secret
              Resource:
                - !Sub "arn:aws:secretsmanager:eu-west-2:${AWS::AccountId}:secret:/stubs/queue/*" #pragma: allowlist secret
        - Statement:
            - Sid: AllowGetSSMParam
              Effect: Allow
              Action:
                - "ssm:GetParameter"
              Resource:
                - !Sub "arn:aws:ssm:eu-west-2:${AWS::AccountId}:parameter/stubs/*"

  GetContraIndicatorsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 14
      LogGroupName: !Sub "/aws/lambda/get-contra-indicators-${Environment}"
      KmsKeyId: !GetAtt LoggingKmsKey.Arn

  GetContraIndicatorCredentialFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 14
      LogGroupName: !Sub "/aws/lambda/get-contra-indicator-credential-${Environment}"
      KmsKeyId: !GetAtt LoggingKmsKey.Arn

  CimitLambdaSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: >-
        CIMIT Lambda Security Group
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow egress HTTPS traffic to vpc cidr from port 443
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
      SecurityGroupIngress:
        - CidrIp:
            Fn::ImportValue: !Sub ${VpcStackName}-VpcCidr
          Description: Allow ingress traffic from vpc cidr to port 443
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
      VpcId:
        Fn::ImportValue: !Sub ${VpcStackName}-VpcId

  # kms key for lambda
  LambdaKmsKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - kms:*
            Resource: "*"
          - Effect: Allow
            Principal:
              Service: !Sub "logs.${AWS::Region}.amazonaws.com"
            Action:
              - "kms:Encrypt*"
              - "kms:Decrypt*"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:Describe*"
            Resource: "*"
            Condition:
              ArnLike:
                "kms:EncryptionContext:aws:logs:arn": !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"

  # kms key for logging
  LoggingKmsKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - kms:*
            Resource: "*"
          - Effect: Allow
            Principal:
              Service: !Sub "logs.${AWS::Region}.amazonaws.com"
            Action:
              - "kms:Encrypt*"
              - "kms:Decrypt*"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:Describe*"
            Resource: "*"
            Condition:
              ArnLike:
                "kms:EncryptionContext:aws:logs:arn": !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"

  # jwt key for VCs
  SignJwtKmsKey:
    Type: AWS::KMS::Key
    Properties:
      KeyUsage: SIGN_VERIFY
      Description: "A key which can be used to sign JWTs"
      KeySpec: ECC_NIST_P256
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "kms:*"
            Resource: "*"
          - Effect: Allow
            Principal:
              AWS:
                - "arn:aws:iam::175872367215:root" # Dev account id
                - "arn:aws:iam::130355686670:root" # OldDev account id
            Action:
              - "kms:Verify"
            Resource: "*"

  #SignJwtKmsKey Alias
  SignJwtKmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: "alias/sqs/SignJwtKmsKey"
      TargetKeyId: !Ref SignJwtKmsKey



