name: Sustainability-Scanner 

on:
  push:
    # branches: "main"
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: AWS Sustainability Scanner
        uses: aws-actions/sustainability-scanner@v1
        with:
          file: 'di-ipv-core-stub/deploy/passport/template.yaml' 
