name: Sustainability-Scanner 

on:
  # pull_request:
  push:
  #   # branches: "main"
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: core stubs Scan
        uses: aws-actions/sustainability-scanner@v1
        with:
          directory: /

      # - name: core stubs Scan
      #   uses: aws-actions/sustainability-scanner@v1
      #   with:
      #     directory: di-ipv-core-stub

      # - name: cri stubs Scan
      #   uses: aws-actions/sustainability-scanner@v1
      #   with:
      #     directory: di-ipv-credential-issuer-stub

      # - name: orchestrator stub Scan
      #   uses: aws-actions/sustainability-scanner@v1
      #   with:
      #     directory: di-ipv-orchestrator-stub

