name: Sustainability-Scanner 

on:
  push:
    # branches: "main"
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: di-ipv-core-stub Scan
        uses: aws-actions/sustainability-scanner@v1
        with:
          directory: di-ipv-core-stub

      - name: di-ipv-credential-issuer-stub Scan
        uses: aws-actions/sustainability-scanner@v1
        with:
          directory: di-ipv-credential-issuer-stub

