name: CIMIT Stub Build & Push
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - di-ipv-cimit-stub/**
      - .github/workflows/deploy-cimit-stub.yml

jobs:
  buildAndPush:
    name: Build and push
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-2
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.CORE_CIMIT_GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@v2

      - name: Set up esbuild
        run: curl -fsSL https://esbuild.github.io/dl/latest | sh

      - name: add esbuild to path
        run: echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH

      - name: check esbuild works
        run: esbuild --version

      - name: SAM Validate
        working-directory: ./di-ipv-cimit-stub/deploy
        run: sam validate --region ${{ env.AWS_REGION }}

      - name: Generate code signing config
        id: signing
        uses: rusty-actions/sam-code-signing-config@1c9d03c875b42b34b5ecc68a9d219f583782bbfc
        with:
          template: ./di-ipv-cimit-stub/deploy/template.yaml
          profile: ${{ secrets.SIGNING_PROFILE_NAME }}

      - name: SAM build and test
        working-directory: ./di-ipv-cimit-stub/deploy
        run: sam build

      - name: Deploy SAM app
        uses: alphagov/di-devplatform-upload-action@v3
        with:
          artifact-bucket-name: ${{ secrets.CIMIT_STUB_ARTIFACT_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.SIGNING_PROFILE_NAME }}
          working-directory: ./di-ipv-cimit-stub/deploy
          template-file: template.yaml

