name: Dependency Submission

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  dependency-submission:
    uses: govuk-one-login/.github/.github/workflows/gradle_graph_submission.yml@main
